# Generated by Django 4.2.16 on 2026-03-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Основной заголовок блока')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок блока')),
                ('channels_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись перед каналами')),
            ],
            options={
                'verbose_name': 'Секция тарифов',
                'verbose_name_plural': 'Секция тарифов',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись под названием')),
                ('accent_badge', models.CharField(blank=True, default='', max_length=255, verbose_name='Акцентный бейдж')),
                ('inherit_line', models.CharField(blank=True, default='', max_length=255, verbose_name='Строка наследования')),
                ('channels', models.TextField(blank=True, default='', verbose_name='Каналы')),
                ('cta_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст кнопки')),
                ('cta_link', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка кнопки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделенная карточка')),
                ('is_dark_card', models.BooleanField(default=False, verbose_name='Темная карточка')),
                ('pricing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricingsection', verbose_name='Секция тарифов')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст пункта')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricing.pricingplan', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Пункт тарифа',
                'verbose_name_plural': 'Пункты тарифа',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
