# Generated by Django 4.2.16 on 2026-03-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegrationsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
            ],
            options={
                'verbose_name': 'Секция интеграции с системами',
                'verbose_name_plural': 'Секция интеграции с системами',
            },
        ),
        migrations.CreateModel(
            name='SystemIntegrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название интеграции')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание интеграции')),
                ('image', models.ImageField(upload_to='system_integrations/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system_integrations.systemintegrationssection', verbose_name='Секция интеграции с системами')),
            ],
            options={
                'verbose_name': 'Пункт интеграции',
                'verbose_name_plural': 'Пункты интеграции',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
