# Generated by Django 4.2.16 on 2026-03-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='header/', verbose_name='Логотип')),
                ('logo_link', models.CharField(max_length=255, verbose_name='Ссылка с логотипа')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Шапка сайта',
                'verbose_name_plural': 'Шапка сайта',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('href', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.siteheader', verbose_name='Шапка сайта')),
            ],
            options={
                'verbose_name': 'Ссылка меню шапки',
                'verbose_name_plural': 'Ссылки меню шапки',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
