# Generated by Django 6.0.3 on 2026-03-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('brand_name', models.CharField(max_length=120, verbose_name='Название бренда')),
                ('brand_href', models.CharField(default='/', max_length=255, verbose_name='Ссылка бренда')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='header/logo/', verbose_name='Логотип (файл)')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Логотип (URL)')),
                ('logo_alt', models.CharField(blank=True, default='', max_length=160, verbose_name='Alt логотипа')),
                ('desktop_nav_aria', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: навигация (десктоп)')),
                ('mobile_dialog_aria', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: диалог меню (мобильное)')),
                ('mobile_nav_aria', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: навигация (мобильное)')),
                ('open_menu_aria', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: открыть меню')),
                ('close_menu_aria', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: закрыть меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шапка сайта',
                'verbose_name_plural': 'Шапка сайта',
            },
        ),
        migrations.CreateModel(
            name='HeaderNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Название пункта')),
                ('href', models.CharField(max_length=255, verbose_name='Ссылка (href)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='core.headersection', verbose_name='Шапка')),
            ],
            options={
                'verbose_name': 'Пункт меню шапки',
                'verbose_name_plural': 'Пункты меню шапки',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeaderSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('aria_label', models.CharField(blank=True, default='', max_length=160, verbose_name='ARIA: описание')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='header/social/', verbose_name='Иконка (файл)')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Иконка (URL)')),
                ('icon_alt', models.CharField(blank=True, default='', max_length=160, verbose_name='Alt иконки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.headersection', verbose_name='Шапка')),
            ],
            options={
                'verbose_name': 'Соцссылка шапки',
                'verbose_name_plural': 'Соцссылки шапки',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
