from django.urls import path

from apps.core.views import (
    AdvantagesSectionAPIView,
    AiValueSectionAPIView,
    ChannelsSectionAPIView,
    ContactsSectionAPIView,
    FooterSectionAPIView,
    HeaderSectionAPIView,
    HeroLogosSectionAPIView,
    HeroSectionAPIView,
    PolicyPageAPIView,
    PricingSectionAPIView,
    ReviewsSectionAPIView,
    SiteDataAPIView,
    SiteSettingsAPIView,
    StepsSectionAPIView,
    health_check,
)

urlpatterns = [
    path("health/", health_check, name="api-health"),
    path("site/", SiteSettingsAPIView.as_view(), name="api-site"),
    path("site-data/", SiteDataAPIView.as_view(), name="api-site-data"),
    path("sections/header/", HeaderSectionAPIView.as_view(), name="api-section-header"),
    path("sections/hero/", HeroSectionAPIView.as_view(), name="api-section-hero"),
    path("sections/hero-logos/", HeroLogosSectionAPIView.as_view(), name="api-section-hero-logos"),
    path("sections/advantages/", AdvantagesSectionAPIView.as_view(), name="api-section-advantages"),
    path("sections/ai-value/", AiValueSectionAPIView.as_view(), name="api-section-ai-value"),
    path("sections/channels/", ChannelsSectionAPIView.as_view(), name="api-section-channels"),
    path("sections/steps/", StepsSectionAPIView.as_view(), name="api-section-steps"),
    path("sections/pricing/", PricingSectionAPIView.as_view(), name="api-section-pricing"),
    path("sections/reviews/", ReviewsSectionAPIView.as_view(), name="api-section-reviews"),
    path("sections/contacts/", ContactsSectionAPIView.as_view(), name="api-section-contacts"),
    path("footer/", FooterSectionAPIView.as_view(), name="api-footer"),
    path("pages/privacy/", PolicyPageAPIView.as_view(), {"slug": "privacy"}, name="api-page-privacy"),
    path("pages/offer/", PolicyPageAPIView.as_view(), {"slug": "offer"}, name="api-page-offer"),
    path("pages/terms/", PolicyPageAPIView.as_view(), {"slug": "terms"}, name="api-page-terms"),
    path("pages/<slug:slug>/", PolicyPageAPIView.as_view(), name="api-page-slug"),
]
