# Generated by Django 4.2.16 on 2026-03-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Первая строка заголовка')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Вторая строка заголовка')),
                ('heading_line_3', models.CharField(max_length=255, verbose_name='Третья строка заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('section_background', models.ImageField(upload_to='contacts/', verbose_name='Фон секции')),
                ('card_background', models.ImageField(upload_to='contacts/', verbose_name='Фон карточки')),
                ('channels_title', models.CharField(max_length=255, verbose_name='Первая строка заголовка карточки')),
                ('channels_subtitle', models.CharField(max_length=255, verbose_name='Вторая строка заголовка карточки')),
            ],
            options={
                'verbose_name': 'Секция контактов',
                'verbose_name_plural': 'Секция контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название канала')),
                ('icon', models.ImageField(upload_to='contacts/icons/', verbose_name='Иконка')),
                ('href', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('contacts_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contacts.contactssection', verbose_name='Секция контактов')),
            ],
            options={
                'verbose_name': 'Канал связи',
                'verbose_name_plural': 'Каналы связи',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
