# Generated by Django 5.2.12 on 2026-03-06 20:51

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelitem',
            name='icon',
            field=models.FileField(upload_to='channels/icons/', validators=[apps.validators.validate_image_or_svg], verbose_name='Иконка'),
        ),
    ]
