# Generated by Django 4.2.16 on 2026-03-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Основной заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='heroblock/', verbose_name='Основное изображение')),
                ('stats_disclaimer', models.TextField(verbose_name='Текст под карточками статистики')),
            ],
            options={
                'verbose_name': 'Hero блок',
                'verbose_name_plural': 'Hero блок',
            },
        ),
        migrations.CreateModel(
            name='HeroStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('hero_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='heroblock.heroblock', verbose_name='Hero блок')),
            ],
            options={
                'verbose_name': 'Показатель Hero-блока',
                'verbose_name_plural': 'Показатели Hero-блока',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
