# Generated by Django 5.2.12 on 2026-03-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionsSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0435\u043a\u0446\u0438\u0438")),
                (
                    "subtitle_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="\u041f\u0440\u0435\u0444\u0438\u043a\u0441 \u043f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0430",
                    ),
                ),
                (
                    "subtitle_highlight",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="\u0410\u043a\u0446\u0435\u043d\u0442\u043d\u0430\u044f \u0447\u0430\u0441\u0442\u044c \u043f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0430",
                    ),
                ),
                (
                    "badge_primary",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="\u041f\u0435\u0440\u0432\u044b\u0439 \u0431\u0435\u0439\u0434\u0436"),
                ),
                (
                    "badge_secondary",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="\u0412\u0442\u043e\u0440\u043e\u0439 \u0431\u0435\u0439\u0434\u0436"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0431\u043b\u043e\u043a\u0430")),
                (
                    "left_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="\u041f\u043e\u0434\u043f\u0438\u0441\u044c \u043b\u0435\u0432\u043e\u0439 \u043a\u043e\u043b\u043e\u043d\u043a\u0438",
                    ),
                ),
                (
                    "right_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="\u041f\u043e\u0434\u043f\u0438\u0441\u044c \u043f\u0440\u0430\u0432\u043e\u0439 \u043a\u043e\u043b\u043e\u043d\u043a\u0438",
                    ),
                ),
                (
                    "paid_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u0440\u0430\u0432\u043e\u0439 \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438",
                    ),
                ),
                (
                    "paid_description",
                    models.TextField(blank=True, default="", verbose_name="\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u0430\u0432\u043e\u0439 \u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0438"),
                ),
                ("note_description", models.TextField(blank=True, default="", verbose_name="\u0422\u0435\u043a\u0441\u0442 \u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u044f")),
            ],
            options={
                "verbose_name": "\u041f\u043b\u0430\u0442\u043d\u044b\u0435 \u0438 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438",
                "verbose_name_plural": "\u041f\u043b\u0430\u0442\u043d\u044b\u0435 \u0438 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500, verbose_name="\u0422\u0435\u043a\u0441\u0442 \u043f\u0443\u043d\u043a\u0442\u0430")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0441\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0438")),
                ("is_active", models.BooleanField(default=True, verbose_name="\u0410\u043a\u0442\u0438\u0432\u043d\u043e")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="subscriptions.subscriptionssection",
                        verbose_name="\u041f\u043b\u0430\u0442\u043d\u044b\u0435 \u0438 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438",
                    ),
                ),
            ],
            options={
                "verbose_name": "\u041f\u0443\u043d\u043a\u0442 \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438",
                "verbose_name_plural": "\u041f\u0443\u043d\u043a\u0442\u044b \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
