# Generated by Django 4.2.16 on 2026-03-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationStepsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок секции')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок секции')),
                ('cta_title_line_1', models.CharField(blank=True, default='', max_length=255, verbose_name='Первая строка CTA')),
                ('cta_title_line_2', models.CharField(blank=True, default='', max_length=255, verbose_name='Вторая строка CTA')),
                ('cta_background', models.ImageField(upload_to='integration_steps/', verbose_name='Фон CTA-карточки')),
                ('cta_image', models.ImageField(upload_to='integration_steps/', verbose_name='Изображение CTA-карточки')),
            ],
            options={
                'verbose_name': 'Этапы интеграции',
                'verbose_name_plural': 'Этапы интеграции',
            },
        ),
        migrations.CreateModel(
            name='IntegrationStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Подпись дня')),
                ('title', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(verbose_name='Описание этапа')),
                ('image', models.ImageField(upload_to='integration_steps/', verbose_name='Изображение этапа')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('steps_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integration_steps.integrationstepssection', verbose_name='Этапы интеграции')),
            ],
            options={
                'verbose_name': 'Этап интеграции',
                'verbose_name_plural': 'Этапы интеграции',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
