# Generated by Django 4.2.16 on 2026-03-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration_steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationstepssection',
            options={'verbose_name': 'Секция этапов интеграции', 'verbose_name_plural': 'Секция этапов интеграции'},
        ),
        migrations.AlterField(
            model_name='integrationstepitem',
            name='steps_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integration_steps.integrationstepssection', verbose_name='Секция этапов интеграции'),
        ),
    ]
