# Generated by Django 5.2.12 on 2026-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Политика конфиденциальности"),
                            ("public_offer", "Публичная оферта"),
                            ("user_agreement", "Пользовательское соглашение"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Технический ключ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("privacy-policy", "Политика конфиденциальности"),
                            ("public-offer", "Публичная оферта"),
                            ("user-agreement", "Пользовательское соглашение"),
                        ],
                        max_length=64,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Текст страницы")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликована")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Страница подвала",
                "verbose_name_plural": "Страницы подвала",
                "ordering": ("key", "id"),
            },
        ),
    ]

