# Generated by Django 5.2.12 on 2026-03-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivenessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=255, verbose_name='Заголовок блока обучения')),
                ('training_right_pill', models.CharField(blank=True, default='', max_length=255, verbose_name='Бейдж справа')),
                ('training_right_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст правой карточки')),
                ('summary_subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок сравнения')),
                ('summary_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок сравнения')),
                ('desktop_stage_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Desktop: заголовок колонки этапа')),
                ('desktop_ai_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Desktop: заголовок колонки AI')),
                ('desktop_human_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Desktop: заголовок колонки Human')),
                ('mobile_ai_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Mobile: подпись AI')),
                ('mobile_human_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Mobile: подпись Human')),
                ('stage_description_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись описания этапа')),
                ('desktop_footer', models.TextField(blank=True, default='', verbose_name='Нижний текст desktop')),
            ],
            options={
                'verbose_name': 'Эффективность',
                'verbose_name_plural': 'Эффективность',
            },
        ),
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('ai_description', models.TextField(blank=True, default='', verbose_name='Описание AI')),
                ('human_description', models.TextField(blank=True, default='', verbose_name='Описание Human')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_items', to='effectiveness.effectivenesssection', verbose_name='Эффективность')),
            ],
            options={
                'verbose_name': 'Пункт сравнения',
                'verbose_name_plural': 'Пункты сравнения',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Текст пункта')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_items', to='effectiveness.effectivenesssection', verbose_name='Эффективность')),
            ],
            options={
                'verbose_name': 'Пункт обучения',
                'verbose_name_plural': 'Пункты обучения',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
