# Generated by Django 4.2.16 on 2026-03-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChannelsSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField(verbose_name="Основной заголовок секции")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Маленький бейдж сверху",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                (
                    "item_aria_label_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Префикс aria-label",
                    ),
                ),
                ("background", models.ImageField(upload_to="channels/", verbose_name="Фоновое изображение")),
                (
                    "image",
                    models.ImageField(upload_to="channels/", verbose_name="Первое большое изображение"),
                ),
                (
                    "secondary_image",
                    models.ImageField(upload_to="channels/", verbose_name="Второе большое изображение"),
                ),
            ],
            options={
                "verbose_name": "Как связаться с нами",
                "verbose_name_plural": "Как связаться с нами",
            },
        ),
        migrations.CreateModel(
            name="ChannelItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название канала")),
                ("icon", models.ImageField(upload_to="channels/icons/", verbose_name="Иконка")),
                ("href", models.CharField(max_length=500, verbose_name="Ссылка")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="channels.channelssection",
                        verbose_name="Как связаться с нами",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал связи",
                "verbose_name_plural": "Каналы связи",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
