# Generated by Django 4.2.16 on 2026-03-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Основной заголовок секции')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Вторая строка заголовка')),
                ('modal_results_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок блока результатов')),
                ('read_more_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст кнопки')),
                ('prev_page_aria', models.CharField(blank=True, default='', max_length=255, verbose_name='Aria-подпись кнопки назад')),
                ('next_page_aria', models.CharField(blank=True, default='', max_length=255, verbose_name='Aria-подпись кнопки вперед')),
                ('pagination_aria', models.CharField(blank=True, default='', max_length=255, verbose_name='Aria-подпись блока пагинации')),
                ('pagination_go_to_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Aria-переход к странице')),
                ('close_modal_aria', models.CharField(blank=True, default='', max_length=255, verbose_name='Aria-подпись кнопки закрытия')),
            ],
            options={
                'verbose_name': 'Секция отзывов',
                'verbose_name_plural': 'Секция отзывов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('person', models.CharField(max_length=255, verbose_name='Подпись')),
                ('preview_text', models.TextField(blank=True, default='', verbose_name='Краткий вводный текст')),
                ('preview_bullets', models.JSONField(blank=True, default=list, verbose_name='Список тезисов превью')),
                ('details_text', models.TextField(blank=True, default='', verbose_name='Полный текст отзыва')),
                ('results', models.JSONField(blank=True, default=list, verbose_name='Список результатов')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('reviews_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews.reviewssection', verbose_name='Секция отзывов')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
