# Generated by Django 5.0 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_briefs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybrief",
            name="preferred_contact_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Предпочтительная дата связи",
            ),
        ),
        migrations.AddField(
            model_name="companybrief",
            name="preferred_contact_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="Предпочтительное время связи",
            ),
        ),
    ]
